### ISSUE TITLE
Unzip failed

### ISSUE THREAD

**Issue by zhuzhizhan** [westerndigitalcorporation/riscv-fw-infrastructure#46]
I try to use command "tar -xvf riscv-llvm-toolchain-debian.tar.gz -C ./WD-Firmware/demo/build/toolchain/" to unzip the file, but an error occur:
$ tar -xvf riscv-gnu-toolchain-debian.tar.gz -C ./WD-Firmware/demo/build/toolchain/
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by JanMatCodasip** [comment]
Please double-check that you have `git-lfs` installed, as noted in the README: https://github.com/westerndigitalcorporation/riscv-fw-infrastructure/blob/master/README.md

**Comment by zhuzhizhan** [comment]
Thanks.
