### ISSUE TITLE
How to build with scons

### ISSUE THREAD

**Issue by zhuzhizhan** [westerndigitalcorporation/riscv-fw-infrastructure#47]
Hi,

I run the ./WD-Firmware/demo/build/config.sh firstly, then run scons. But an error occur:
scons: Reading SConscript files ...
Setting Demo to => multi_harts (gcc)
Setting GCC Toolchain to => /home/zzz/code/riscv/riscv-fw-infrastructure/WD-Firmware/demo/build/toolchain/gcc
Error:  Unsupported target []
Error:  Currently supporting hifive1 | hifive-un | eh1 | eh2 | el2

So do someone how to set the target?

**Comment by feiger313** [comment]
> Hi,
> 
> I run the ./WD-Firmware/demo/build/config.sh firstly, then run scons. But an error occur:
> scons: Reading SConscript files ...
> Setting Demo to => multi_harts (gcc)
> Setting GCC Toolchain to => /home/zzz/code/riscv/riscv-fw-infrastructure/WD-Firmware/demo/build/toolchain/gcc
> Error: Unsupported target []
> Error: Currently supporting hifive1 | hifive-un | eh1 | eh2 | el2
> 
> So do someone how to set the target?

eg:  scons target=el2

**Comment by ronen-haen-sndk** [comment]
zhuzhizhan, did you manage to build with scons as suggested by feiger313 (```scons target=el2```)?

**Comment by zhuzhizhan** [comment]
> zhuzhizhan, did you manage to build with scons as suggested by feiger313 (`scons target=el2`)?

Yes.
