### ISSUE TITLE
Communicate with host when using simulator(whisper) required

### ISSUE THREAD

**Issue by antiwinter** [westerndigitalcorporation/riscv-fw-infrastructure#52]
Is there a way that I can read input from the host when using the simulator (whisper)? I've checked the UART driver in the **bsp** folder, it only provides the **printf** function, no **getc** function is provided.

Every possible method is acceptable, e.g:

* UART: need to provide the **getc** in **bsp**, and a way to send input to whisper from host
* A file on **host**, which may possibly be presented from within **el2** as a piece of memory

**Comment by oferShinaar** [comment]
Whisper and the HW UART on SweRV support stdio, including inputs.
But the BSP does not support it yet, as you noticed, there is no ```getc()```.
We will include this feature in the future, but if you already have any implementation done, you can create a PR, and we will merge it.

**Comment by antiwinter** [comment]
Thank you for your response. I don't know whether whisper redirected input before. Since you've confirmed that, I can have a try to implement `getc()`

**Comment by oferShinaar** [comment]
Thanks...
but if you are willing to wait, we will have it open source at the begging of next week

**Comment by antiwinter** [comment]
Good, I choose to wait :)

**Comment by oferShinaar** [comment]
getchar is now supported #28591ba4de (also in the master branch)
You can get it from ```bsp_pritnf.c \ uartGetchar()```  
There is a new demo to run it, just in demo_getchar.py remove `x` from `xD_NONE_AUTOMATION`

**Comment by oferShinaar** [comment]
solved
